version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      nodejs: 10
    commands:
      - echo Entered the install phase...
      - npm install
      - npm install -g serverless
    finally:
      - echo Completed the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo Completed the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - sls package
      - sls deploy function -f getParameter
      - sls deploy function -f getRemoteConfig
    finally:
      - echo Completed the build phase...
artifacts:
  files:
    - './target/feature-flags-test-dev.jar'
  name: feature-flags-test-$(date +%Y-%m-%d)


